@baseUrl = http://localhost:8080/api

# ~~~~~~~~~~~~~~~~~~~ Fetch Products endpoint ~~~~~~~~~~~~~~~~~~~~~

GET {{baseUrl}}/products HTTP/1.1
Content-Type: application/json

###

# ~~~~~~~~~~~~~~~~~~~ Fetch one Product endpoint ~~~~~~~~~~~~~~~~~~~~

GET {{baseUrl}}/products/5fc122ac8045e20ef8dce74a HTTP/1.1
Content-Type: application/json


###

# ~~~~~~~~~~~~~~~~~~~ Add a new Product endpoint ~~~~~~~~~~~~~~~~~~

POST {{baseUrl}}/products HTTP/1.1
Content-Type: multipart/form-data;"

//TODO add productImage in Rest Client extenxtion

{
    "name": "test",
    "price": 100,
    "productImage": ""
}

###

# ~~~~~~~~~~~~~~~~~~~ Delete a Product endpoint ~~~~~~~~~~~~~~~~~~~

DELETE {{baseUrl}}/products/5cc82927e6bf213bf463c65d HTTP/1.1
Authorization: token 
Content-Type: application/json

###
