@baseUrl = http://localhost:8080/api
@mockEmail = "chalvantzis12@outlook.com"
@mockPassword = "testtest12"
@userId = 

POST {{baseUrl}}/user/signup HTTP/1.1
content-type: application/json

{
    "email": {{mockEmail}},
    "password": {{mockPassword}}
}

###

POST {{baseUrl}}/user/login HTTP/1.1
content-type: application/json

{
    "email": {{mockEmail}},
    "password": {{mockPassword}}
}


###

DELETE {{baseUrl}}/user/{{userId}} HTTP/1.1
content-type: application/json
